// Code generated by protoc-gen-gogo.
// source: data.proto
// DO NOT EDIT!

/*
	Package gogoslick is a generated protocol buffer package.

	It is generated from these files:
		data.proto

	It has these top-level messages:
		GoGoSlickBasicMemInfo
		GoGoSlickMemInfo
		GoGoSlickMessage
		GoGoSlickRedditAccount
		GoGoSlickAccountData
		GoGoSlickCPUInfo
		GoGoSlickCPU
*/
package gogoslick

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GoGoSlickBasicMemInfo struct {
	MemTotal     int64 `protobuf:"varint,1,opt,name=MemTotal,json=memTotal,proto3" json:"MemTotal,omitempty"`
	MemFree      int64 `protobuf:"varint,2,opt,name=MemFree,json=memFree,proto3" json:"MemFree,omitempty"`
	MemAvailable int64 `protobuf:"varint,3,opt,name=MemAvailable,json=memAvailable,proto3" json:"MemAvailable,omitempty"`
	Buffers      int64 `protobuf:"varint,4,opt,name=Buffers,json=buffers,proto3" json:"Buffers,omitempty"`
	Cached       int64 `protobuf:"varint,5,opt,name=Cached,json=cached,proto3" json:"Cached,omitempty"`
	SwapCached   int64 `protobuf:"varint,6,opt,name=SwapCached,json=swapCached,proto3" json:"SwapCached,omitempty"`
	SwapTotal    int64 `protobuf:"varint,7,opt,name=SwapTotal,json=swapTotal,proto3" json:"SwapTotal,omitempty"`
	SwapFree     int64 `protobuf:"varint,8,opt,name=SwapFree,json=swapFree,proto3" json:"SwapFree,omitempty"`
}

func (m *GoGoSlickBasicMemInfo) Reset()                    { *m = GoGoSlickBasicMemInfo{} }
func (m *GoGoSlickBasicMemInfo) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickBasicMemInfo) ProtoMessage()               {}
func (*GoGoSlickBasicMemInfo) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{0} }

type GoGoSlickMemInfo struct {
	MemTotal          int64 `protobuf:"varint,1,opt,name=MemTotal,json=memTotal,proto3" json:"MemTotal,omitempty"`
	MemFree           int64 `protobuf:"varint,2,opt,name=MemFree,json=memFree,proto3" json:"MemFree,omitempty"`
	MemAvailable      int64 `protobuf:"varint,3,opt,name=MemAvailable,json=memAvailable,proto3" json:"MemAvailable,omitempty"`
	Buffers           int64 `protobuf:"varint,4,opt,name=Buffers,json=buffers,proto3" json:"Buffers,omitempty"`
	Cached            int64 `protobuf:"varint,5,opt,name=Cached,json=cached,proto3" json:"Cached,omitempty"`
	SwapCached        int64 `protobuf:"varint,6,opt,name=SwapCached,json=swapCached,proto3" json:"SwapCached,omitempty"`
	Active            int64 `protobuf:"varint,7,opt,name=Active,json=active,proto3" json:"Active,omitempty"`
	Inactive          int64 `protobuf:"varint,8,opt,name=Inactive,json=inactive,proto3" json:"Inactive,omitempty"`
	ActiveAnon        int64 `protobuf:"varint,9,opt,name=ActiveAnon,json=activeAnon,proto3" json:"ActiveAnon,omitempty"`
	InactiveAnon      int64 `protobuf:"varint,10,opt,name=InactiveAnon,json=inactiveAnon,proto3" json:"InactiveAnon,omitempty"`
	ActiveFile        int64 `protobuf:"varint,11,opt,name=ActiveFile,json=activeFile,proto3" json:"ActiveFile,omitempty"`
	InactiveFile      int64 `protobuf:"varint,12,opt,name=InactiveFile,json=inactiveFile,proto3" json:"InactiveFile,omitempty"`
	Unevictable       int64 `protobuf:"varint,13,opt,name=Unevictable,json=unevictable,proto3" json:"Unevictable,omitempty"`
	Mlocked           int64 `protobuf:"varint,14,opt,name=Mlocked,json=mlocked,proto3" json:"Mlocked,omitempty"`
	SwapTotal         int64 `protobuf:"varint,15,opt,name=SwapTotal,json=swapTotal,proto3" json:"SwapTotal,omitempty"`
	SwapFree          int64 `protobuf:"varint,16,opt,name=SwapFree,json=swapFree,proto3" json:"SwapFree,omitempty"`
	Dirty             int64 `protobuf:"varint,17,opt,name=Dirty,json=dirty,proto3" json:"Dirty,omitempty"`
	Writeback         int64 `protobuf:"varint,18,opt,name=Writeback,json=writeback,proto3" json:"Writeback,omitempty"`
	AnonPages         int64 `protobuf:"varint,19,opt,name=AnonPages,json=anonPages,proto3" json:"AnonPages,omitempty"`
	Mapped            int64 `protobuf:"varint,20,opt,name=Mapped,json=mapped,proto3" json:"Mapped,omitempty"`
	Shmem             int64 `protobuf:"varint,21,opt,name=Shmem,json=shmem,proto3" json:"Shmem,omitempty"`
	Slab              int64 `protobuf:"varint,22,opt,name=Slab,json=slab,proto3" json:"Slab,omitempty"`
	SReclaimable      int64 `protobuf:"varint,23,opt,name=SReclaimable,json=sReclaimable,proto3" json:"SReclaimable,omitempty"`
	SUnreclaim        int64 `protobuf:"varint,24,opt,name=SUnreclaim,json=sUnreclaim,proto3" json:"SUnreclaim,omitempty"`
	KernelStack       int64 `protobuf:"varint,25,opt,name=KernelStack,json=kernelStack,proto3" json:"KernelStack,omitempty"`
	NFSUnstable       int64 `protobuf:"varint,26,opt,name=NFSUnstable,json=nFSUnstable,proto3" json:"NFSUnstable,omitempty"`
	Bounce            int64 `protobuf:"varint,27,opt,name=Bounce,json=bounce,proto3" json:"Bounce,omitempty"`
	WritebackTmp      int64 `protobuf:"varint,28,opt,name=WritebackTmp,json=writebackTmp,proto3" json:"WritebackTmp,omitempty"`
	CommitLimit       int64 `protobuf:"varint,29,opt,name=CommitLimit,json=commitLimit,proto3" json:"CommitLimit,omitempty"`
	VmallocTotal      int64 `protobuf:"varint,30,opt,name=VmallocTotal,json=vmallocTotal,proto3" json:"VmallocTotal,omitempty"`
	VmallocUsed       int64 `protobuf:"varint,31,opt,name=VmallocUsed,json=vmallocUsed,proto3" json:"VmallocUsed,omitempty"`
	VmallocChunk      int64 `protobuf:"varint,32,opt,name=VmallocChunk,json=vmallocChunk,proto3" json:"VmallocChunk,omitempty"`
	HardwareCorrupted int64 `protobuf:"varint,33,opt,name=HardwareCorrupted,json=hardwareCorrupted,proto3" json:"HardwareCorrupted,omitempty"`
	AnonHugePages     int64 `protobuf:"varint,34,opt,name=AnonHugePages,json=anonHugePages,proto3" json:"AnonHugePages,omitempty"`
	HugePagesTotal    int64 `protobuf:"varint,35,opt,name=HugePagesTotal,json=hugePagesTotal,proto3" json:"HugePagesTotal,omitempty"`
	HugePagesFree     int64 `protobuf:"varint,36,opt,name=HugePagesFree,json=hugePagesFree,proto3" json:"HugePagesFree,omitempty"`
	HugePagesRsvd     int64 `protobuf:"varint,37,opt,name=HugePagesRsvd,json=hugePagesRsvd,proto3" json:"HugePagesRsvd,omitempty"`
	Hugepagesize      int64 `protobuf:"varint,38,opt,name=Hugepagesize,json=hugepagesize,proto3" json:"Hugepagesize,omitempty"`
	DirectMap4K       int64 `protobuf:"varint,39,opt,name=DirectMap4k,json=directMap4k,proto3" json:"DirectMap4k,omitempty"`
	DirectMap2M       int64 `protobuf:"varint,40,opt,name=DirectMap2M,json=directMap2M,proto3" json:"DirectMap2M,omitempty"`
}

func (m *GoGoSlickMemInfo) Reset()                    { *m = GoGoSlickMemInfo{} }
func (m *GoGoSlickMemInfo) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickMemInfo) ProtoMessage()               {}
func (*GoGoSlickMemInfo) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{1} }

type GoGoSlickMessage struct {
	ID     []byte `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	DestID uint32 `protobuf:"varint,2,opt,name=DestID,json=destID,proto3" json:"DestID,omitempty"`
	Type   int32  `protobuf:"varint,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Kind   int32  `protobuf:"varint,4,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`
	Data   []byte `protobuf:"bytes,5,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *GoGoSlickMessage) Reset()                    { *m = GoGoSlickMessage{} }
func (m *GoGoSlickMessage) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickMessage) ProtoMessage()               {}
func (*GoGoSlickMessage) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{2} }

type GoGoSlickRedditAccount struct {
	ID   string                `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name string                `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Kind string                `protobuf:"bytes,3,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`
	Data *GoGoSlickAccountData `protobuf:"bytes,4,opt,name=Data,json=data" json:"Data,omitempty"`
}

func (m *GoGoSlickRedditAccount) Reset()                    { *m = GoGoSlickRedditAccount{} }
func (m *GoGoSlickRedditAccount) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickRedditAccount) ProtoMessage()               {}
func (*GoGoSlickRedditAccount) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{3} }

func (m *GoGoSlickRedditAccount) GetData() *GoGoSlickAccountData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GoGoSlickAccountData struct {
	CommentKarma int64  `protobuf:"varint,1,opt,name=CommentKarma,json=commentKarma,proto3" json:"CommentKarma,omitempty"`
	HasMail      bool   `protobuf:"varint,2,opt,name=HasMail,json=hasMail,proto3" json:"HasMail,omitempty"`
	HasModMail   bool   `protobuf:"varint,3,opt,name=HasModMail,json=hasModMail,proto3" json:"HasModMail,omitempty"`
	ID           string `protobuf:"bytes,4,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	InboxCount   int64  `protobuf:"varint,5,opt,name=InboxCount,json=inboxCount,proto3" json:"InboxCount,omitempty"`
	IsFriend     bool   `protobuf:"varint,6,opt,name=IsFriend,json=isFriend,proto3" json:"IsFriend,omitempty"`
	IsGold       bool   `protobuf:"varint,7,opt,name=IsGold,json=isGold,proto3" json:"IsGold,omitempty"`
	LinkKarma    int64  `protobuf:"varint,8,opt,name=LinkKarma,json=linkKarma,proto3" json:"LinkKarma,omitempty"`
	ModHash      string `protobuf:"bytes,9,opt,name=ModHash,json=modHash,proto3" json:"ModHash,omitempty"`
	Name         string `protobuf:"bytes,10,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Over18       bool   `protobuf:"varint,11,opt,name=Over18,json=over18,proto3" json:"Over18,omitempty"`
}

func (m *GoGoSlickAccountData) Reset()                    { *m = GoGoSlickAccountData{} }
func (m *GoGoSlickAccountData) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickAccountData) ProtoMessage()               {}
func (*GoGoSlickAccountData) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{4} }

type GoGoSlickCPUInfo struct {
	CPUs []*GoGoSlickCPU `protobuf:"bytes,1,rep,name=CPUs,json=cPUs" json:"CPUs,omitempty"`
}

func (m *GoGoSlickCPUInfo) Reset()                    { *m = GoGoSlickCPUInfo{} }
func (m *GoGoSlickCPUInfo) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickCPUInfo) ProtoMessage()               {}
func (*GoGoSlickCPUInfo) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{5} }

func (m *GoGoSlickCPUInfo) GetCPUs() []*GoGoSlickCPU {
	if m != nil {
		return m.CPUs
	}
	return nil
}

type GoGoSlickCPU struct {
	Processor       int32   `protobuf:"varint,1,opt,name=Processor,json=processor,proto3" json:"Processor,omitempty"`
	VendorID        string  `protobuf:"bytes,2,opt,name=VendorID,json=vendorID,proto3" json:"VendorID,omitempty"`
	CPUFamily       string  `protobuf:"bytes,3,opt,name=CPUFamily,json=cPUFamily,proto3" json:"CPUFamily,omitempty"`
	Model           string  `protobuf:"bytes,4,opt,name=Model,json=model,proto3" json:"Model,omitempty"`
	ModelName       string  `protobuf:"bytes,5,opt,name=ModelName,json=modelName,proto3" json:"ModelName,omitempty"`
	Stepping        string  `protobuf:"bytes,6,opt,name=Stepping,json=stepping,proto3" json:"Stepping,omitempty"`
	Microcode       string  `protobuf:"bytes,7,opt,name=Microcode,json=microcode,proto3" json:"Microcode,omitempty"`
	CPUMHz          float32 `protobuf:"fixed32,8,opt,name=CPUMHz,json=cPUMHz,proto3" json:"CPUMHz,omitempty"`
	CacheSize       string  `protobuf:"bytes,9,opt,name=CacheSize,json=cacheSize,proto3" json:"CacheSize,omitempty"`
	PhysicalID      int32   `protobuf:"varint,10,opt,name=PhysicalID,json=physicalID,proto3" json:"PhysicalID,omitempty"`
	Siblings        int32   `protobuf:"varint,11,opt,name=Siblings,json=siblings,proto3" json:"Siblings,omitempty"`
	CoreID          int32   `protobuf:"varint,12,opt,name=CoreID,json=coreID,proto3" json:"CoreID,omitempty"`
	CPUCores        int32   `protobuf:"varint,13,opt,name=CPUCores,json=cPUCores,proto3" json:"CPUCores,omitempty"`
	ApicID          int32   `protobuf:"varint,14,opt,name=ApicID,json=apicID,proto3" json:"ApicID,omitempty"`
	InitialApicID   int32   `protobuf:"varint,15,opt,name=InitialApicID,json=initialApicID,proto3" json:"InitialApicID,omitempty"`
	FPU             string  `protobuf:"bytes,16,opt,name=FPU,json=fPU,proto3" json:"FPU,omitempty"`
	FPUException    string  `protobuf:"bytes,17,opt,name=FPUException,json=fPUException,proto3" json:"FPUException,omitempty"`
	CPUIDLevel      string  `protobuf:"bytes,18,opt,name=CPUIDLevel,json=cPUIDLevel,proto3" json:"CPUIDLevel,omitempty"`
	WP              string  `protobuf:"bytes,19,opt,name=WP,json=wP,proto3" json:"WP,omitempty"`
	Flags           string  `protobuf:"bytes,21,opt,name=Flags,json=flags,proto3" json:"Flags,omitempty"`
	BogoMIPS        float32 `protobuf:"fixed32,22,opt,name=BogoMIPS,json=bogoMIPS,proto3" json:"BogoMIPS,omitempty"`
	CLFlushSize     string  `protobuf:"bytes,23,opt,name=CLFlushSize,json=cLFlushSize,proto3" json:"CLFlushSize,omitempty"`
	CacheAlignment  string  `protobuf:"bytes,24,opt,name=CacheAlignment,json=cacheAlignment,proto3" json:"CacheAlignment,omitempty"`
	AddressSizes    string  `protobuf:"bytes,25,opt,name=AddressSizes,json=addressSizes,proto3" json:"AddressSizes,omitempty"`
	PowerManagement string  `protobuf:"bytes,26,opt,name=PowerManagement,json=powerManagement,proto3" json:"PowerManagement,omitempty"`
}

func (m *GoGoSlickCPU) Reset()                    { *m = GoGoSlickCPU{} }
func (m *GoGoSlickCPU) String() string            { return proto.CompactTextString(m) }
func (*GoGoSlickCPU) ProtoMessage()               {}
func (*GoGoSlickCPU) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{6} }

func init() {
	proto.RegisterType((*GoGoSlickBasicMemInfo)(nil), "protobuf.GoGoSlickBasicMemInfo")
	proto.RegisterType((*GoGoSlickMemInfo)(nil), "protobuf.GoGoSlickMemInfo")
	proto.RegisterType((*GoGoSlickMessage)(nil), "protobuf.GoGoSlickMessage")
	proto.RegisterType((*GoGoSlickRedditAccount)(nil), "protobuf.GoGoSlickRedditAccount")
	proto.RegisterType((*GoGoSlickAccountData)(nil), "protobuf.GoGoSlickAccountData")
	proto.RegisterType((*GoGoSlickCPUInfo)(nil), "protobuf.GoGoSlickCPUInfo")
	proto.RegisterType((*GoGoSlickCPU)(nil), "protobuf.GoGoSlickCPU")
}
func (m *GoGoSlickBasicMemInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickBasicMemInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MemTotal != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintData(data, i, uint64(m.MemTotal))
	}
	if m.MemFree != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintData(data, i, uint64(m.MemFree))
	}
	if m.MemAvailable != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintData(data, i, uint64(m.MemAvailable))
	}
	if m.Buffers != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintData(data, i, uint64(m.Buffers))
	}
	if m.Cached != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintData(data, i, uint64(m.Cached))
	}
	if m.SwapCached != 0 {
		data[i] = 0x30
		i++
		i = encodeVarintData(data, i, uint64(m.SwapCached))
	}
	if m.SwapTotal != 0 {
		data[i] = 0x38
		i++
		i = encodeVarintData(data, i, uint64(m.SwapTotal))
	}
	if m.SwapFree != 0 {
		data[i] = 0x40
		i++
		i = encodeVarintData(data, i, uint64(m.SwapFree))
	}
	return i, nil
}

func (m *GoGoSlickMemInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickMemInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MemTotal != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintData(data, i, uint64(m.MemTotal))
	}
	if m.MemFree != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintData(data, i, uint64(m.MemFree))
	}
	if m.MemAvailable != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintData(data, i, uint64(m.MemAvailable))
	}
	if m.Buffers != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintData(data, i, uint64(m.Buffers))
	}
	if m.Cached != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintData(data, i, uint64(m.Cached))
	}
	if m.SwapCached != 0 {
		data[i] = 0x30
		i++
		i = encodeVarintData(data, i, uint64(m.SwapCached))
	}
	if m.Active != 0 {
		data[i] = 0x38
		i++
		i = encodeVarintData(data, i, uint64(m.Active))
	}
	if m.Inactive != 0 {
		data[i] = 0x40
		i++
		i = encodeVarintData(data, i, uint64(m.Inactive))
	}
	if m.ActiveAnon != 0 {
		data[i] = 0x48
		i++
		i = encodeVarintData(data, i, uint64(m.ActiveAnon))
	}
	if m.InactiveAnon != 0 {
		data[i] = 0x50
		i++
		i = encodeVarintData(data, i, uint64(m.InactiveAnon))
	}
	if m.ActiveFile != 0 {
		data[i] = 0x58
		i++
		i = encodeVarintData(data, i, uint64(m.ActiveFile))
	}
	if m.InactiveFile != 0 {
		data[i] = 0x60
		i++
		i = encodeVarintData(data, i, uint64(m.InactiveFile))
	}
	if m.Unevictable != 0 {
		data[i] = 0x68
		i++
		i = encodeVarintData(data, i, uint64(m.Unevictable))
	}
	if m.Mlocked != 0 {
		data[i] = 0x70
		i++
		i = encodeVarintData(data, i, uint64(m.Mlocked))
	}
	if m.SwapTotal != 0 {
		data[i] = 0x78
		i++
		i = encodeVarintData(data, i, uint64(m.SwapTotal))
	}
	if m.SwapFree != 0 {
		data[i] = 0x80
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.SwapFree))
	}
	if m.Dirty != 0 {
		data[i] = 0x88
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Dirty))
	}
	if m.Writeback != 0 {
		data[i] = 0x90
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Writeback))
	}
	if m.AnonPages != 0 {
		data[i] = 0x98
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.AnonPages))
	}
	if m.Mapped != 0 {
		data[i] = 0xa0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Mapped))
	}
	if m.Shmem != 0 {
		data[i] = 0xa8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Shmem))
	}
	if m.Slab != 0 {
		data[i] = 0xb0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Slab))
	}
	if m.SReclaimable != 0 {
		data[i] = 0xb8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.SReclaimable))
	}
	if m.SUnreclaim != 0 {
		data[i] = 0xc0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.SUnreclaim))
	}
	if m.KernelStack != 0 {
		data[i] = 0xc8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.KernelStack))
	}
	if m.NFSUnstable != 0 {
		data[i] = 0xd0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.NFSUnstable))
	}
	if m.Bounce != 0 {
		data[i] = 0xd8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.Bounce))
	}
	if m.WritebackTmp != 0 {
		data[i] = 0xe0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.WritebackTmp))
	}
	if m.CommitLimit != 0 {
		data[i] = 0xe8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.CommitLimit))
	}
	if m.VmallocTotal != 0 {
		data[i] = 0xf0
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.VmallocTotal))
	}
	if m.VmallocUsed != 0 {
		data[i] = 0xf8
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(m.VmallocUsed))
	}
	if m.VmallocChunk != 0 {
		data[i] = 0x80
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.VmallocChunk))
	}
	if m.HardwareCorrupted != 0 {
		data[i] = 0x88
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.HardwareCorrupted))
	}
	if m.AnonHugePages != 0 {
		data[i] = 0x90
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.AnonHugePages))
	}
	if m.HugePagesTotal != 0 {
		data[i] = 0x98
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.HugePagesTotal))
	}
	if m.HugePagesFree != 0 {
		data[i] = 0xa0
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.HugePagesFree))
	}
	if m.HugePagesRsvd != 0 {
		data[i] = 0xa8
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.HugePagesRsvd))
	}
	if m.Hugepagesize != 0 {
		data[i] = 0xb0
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.Hugepagesize))
	}
	if m.DirectMap4K != 0 {
		data[i] = 0xb8
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.DirectMap4K))
	}
	if m.DirectMap2M != 0 {
		data[i] = 0xc0
		i++
		data[i] = 0x2
		i++
		i = encodeVarintData(data, i, uint64(m.DirectMap2M))
	}
	return i, nil
}

func (m *GoGoSlickMessage) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickMessage) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintData(data, i, uint64(len(m.ID)))
		i += copy(data[i:], m.ID)
	}
	if m.DestID != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintData(data, i, uint64(m.DestID))
	}
	if m.Type != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintData(data, i, uint64(m.Type))
	}
	if m.Kind != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintData(data, i, uint64(m.Kind))
	}
	if len(m.Data) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintData(data, i, uint64(len(m.Data)))
		i += copy(data[i:], m.Data)
	}
	return i, nil
}

func (m *GoGoSlickRedditAccount) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickRedditAccount) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintData(data, i, uint64(len(m.ID)))
		i += copy(data[i:], m.ID)
	}
	if len(m.Name) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintData(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if len(m.Kind) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintData(data, i, uint64(len(m.Kind)))
		i += copy(data[i:], m.Kind)
	}
	if m.Data != nil {
		data[i] = 0x22
		i++
		i = encodeVarintData(data, i, uint64(m.Data.Size()))
		n1, err := m.Data.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *GoGoSlickAccountData) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickAccountData) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CommentKarma != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintData(data, i, uint64(m.CommentKarma))
	}
	if m.HasMail {
		data[i] = 0x10
		i++
		if m.HasMail {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.HasModMail {
		data[i] = 0x18
		i++
		if m.HasModMail {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if len(m.ID) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintData(data, i, uint64(len(m.ID)))
		i += copy(data[i:], m.ID)
	}
	if m.InboxCount != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintData(data, i, uint64(m.InboxCount))
	}
	if m.IsFriend {
		data[i] = 0x30
		i++
		if m.IsFriend {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.IsGold {
		data[i] = 0x38
		i++
		if m.IsGold {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.LinkKarma != 0 {
		data[i] = 0x40
		i++
		i = encodeVarintData(data, i, uint64(m.LinkKarma))
	}
	if len(m.ModHash) > 0 {
		data[i] = 0x4a
		i++
		i = encodeVarintData(data, i, uint64(len(m.ModHash)))
		i += copy(data[i:], m.ModHash)
	}
	if len(m.Name) > 0 {
		data[i] = 0x52
		i++
		i = encodeVarintData(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if m.Over18 {
		data[i] = 0x58
		i++
		if m.Over18 {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *GoGoSlickCPUInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickCPUInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.CPUs) > 0 {
		for _, msg := range m.CPUs {
			data[i] = 0xa
			i++
			i = encodeVarintData(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *GoGoSlickCPU) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *GoGoSlickCPU) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Processor != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintData(data, i, uint64(m.Processor))
	}
	if len(m.VendorID) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintData(data, i, uint64(len(m.VendorID)))
		i += copy(data[i:], m.VendorID)
	}
	if len(m.CPUFamily) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintData(data, i, uint64(len(m.CPUFamily)))
		i += copy(data[i:], m.CPUFamily)
	}
	if len(m.Model) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintData(data, i, uint64(len(m.Model)))
		i += copy(data[i:], m.Model)
	}
	if len(m.ModelName) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintData(data, i, uint64(len(m.ModelName)))
		i += copy(data[i:], m.ModelName)
	}
	if len(m.Stepping) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintData(data, i, uint64(len(m.Stepping)))
		i += copy(data[i:], m.Stepping)
	}
	if len(m.Microcode) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintData(data, i, uint64(len(m.Microcode)))
		i += copy(data[i:], m.Microcode)
	}
	if m.CPUMHz != 0 {
		data[i] = 0x45
		i++
		i = encodeFixed32Data(data, i, uint32(math.Float32bits(float32(m.CPUMHz))))
	}
	if len(m.CacheSize) > 0 {
		data[i] = 0x4a
		i++
		i = encodeVarintData(data, i, uint64(len(m.CacheSize)))
		i += copy(data[i:], m.CacheSize)
	}
	if m.PhysicalID != 0 {
		data[i] = 0x50
		i++
		i = encodeVarintData(data, i, uint64(m.PhysicalID))
	}
	if m.Siblings != 0 {
		data[i] = 0x58
		i++
		i = encodeVarintData(data, i, uint64(m.Siblings))
	}
	if m.CoreID != 0 {
		data[i] = 0x60
		i++
		i = encodeVarintData(data, i, uint64(m.CoreID))
	}
	if m.CPUCores != 0 {
		data[i] = 0x68
		i++
		i = encodeVarintData(data, i, uint64(m.CPUCores))
	}
	if m.ApicID != 0 {
		data[i] = 0x70
		i++
		i = encodeVarintData(data, i, uint64(m.ApicID))
	}
	if m.InitialApicID != 0 {
		data[i] = 0x78
		i++
		i = encodeVarintData(data, i, uint64(m.InitialApicID))
	}
	if len(m.FPU) > 0 {
		data[i] = 0x82
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.FPU)))
		i += copy(data[i:], m.FPU)
	}
	if len(m.FPUException) > 0 {
		data[i] = 0x8a
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.FPUException)))
		i += copy(data[i:], m.FPUException)
	}
	if len(m.CPUIDLevel) > 0 {
		data[i] = 0x92
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.CPUIDLevel)))
		i += copy(data[i:], m.CPUIDLevel)
	}
	if len(m.WP) > 0 {
		data[i] = 0x9a
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.WP)))
		i += copy(data[i:], m.WP)
	}
	if len(m.Flags) > 0 {
		data[i] = 0xaa
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.Flags)))
		i += copy(data[i:], m.Flags)
	}
	if m.BogoMIPS != 0 {
		data[i] = 0xb5
		i++
		data[i] = 0x1
		i++
		i = encodeFixed32Data(data, i, uint32(math.Float32bits(float32(m.BogoMIPS))))
	}
	if len(m.CLFlushSize) > 0 {
		data[i] = 0xba
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.CLFlushSize)))
		i += copy(data[i:], m.CLFlushSize)
	}
	if len(m.CacheAlignment) > 0 {
		data[i] = 0xc2
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.CacheAlignment)))
		i += copy(data[i:], m.CacheAlignment)
	}
	if len(m.AddressSizes) > 0 {
		data[i] = 0xca
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.AddressSizes)))
		i += copy(data[i:], m.AddressSizes)
	}
	if len(m.PowerManagement) > 0 {
		data[i] = 0xd2
		i++
		data[i] = 0x1
		i++
		i = encodeVarintData(data, i, uint64(len(m.PowerManagement)))
		i += copy(data[i:], m.PowerManagement)
	}
	return i, nil
}

func encodeFixed64Data(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Data(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintData(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *GoGoSlickBasicMemInfo) Size() (n int) {
	var l int
	_ = l
	if m.MemTotal != 0 {
		n += 1 + sovData(uint64(m.MemTotal))
	}
	if m.MemFree != 0 {
		n += 1 + sovData(uint64(m.MemFree))
	}
	if m.MemAvailable != 0 {
		n += 1 + sovData(uint64(m.MemAvailable))
	}
	if m.Buffers != 0 {
		n += 1 + sovData(uint64(m.Buffers))
	}
	if m.Cached != 0 {
		n += 1 + sovData(uint64(m.Cached))
	}
	if m.SwapCached != 0 {
		n += 1 + sovData(uint64(m.SwapCached))
	}
	if m.SwapTotal != 0 {
		n += 1 + sovData(uint64(m.SwapTotal))
	}
	if m.SwapFree != 0 {
		n += 1 + sovData(uint64(m.SwapFree))
	}
	return n
}

func (m *GoGoSlickMemInfo) Size() (n int) {
	var l int
	_ = l
	if m.MemTotal != 0 {
		n += 1 + sovData(uint64(m.MemTotal))
	}
	if m.MemFree != 0 {
		n += 1 + sovData(uint64(m.MemFree))
	}
	if m.MemAvailable != 0 {
		n += 1 + sovData(uint64(m.MemAvailable))
	}
	if m.Buffers != 0 {
		n += 1 + sovData(uint64(m.Buffers))
	}
	if m.Cached != 0 {
		n += 1 + sovData(uint64(m.Cached))
	}
	if m.SwapCached != 0 {
		n += 1 + sovData(uint64(m.SwapCached))
	}
	if m.Active != 0 {
		n += 1 + sovData(uint64(m.Active))
	}
	if m.Inactive != 0 {
		n += 1 + sovData(uint64(m.Inactive))
	}
	if m.ActiveAnon != 0 {
		n += 1 + sovData(uint64(m.ActiveAnon))
	}
	if m.InactiveAnon != 0 {
		n += 1 + sovData(uint64(m.InactiveAnon))
	}
	if m.ActiveFile != 0 {
		n += 1 + sovData(uint64(m.ActiveFile))
	}
	if m.InactiveFile != 0 {
		n += 1 + sovData(uint64(m.InactiveFile))
	}
	if m.Unevictable != 0 {
		n += 1 + sovData(uint64(m.Unevictable))
	}
	if m.Mlocked != 0 {
		n += 1 + sovData(uint64(m.Mlocked))
	}
	if m.SwapTotal != 0 {
		n += 1 + sovData(uint64(m.SwapTotal))
	}
	if m.SwapFree != 0 {
		n += 2 + sovData(uint64(m.SwapFree))
	}
	if m.Dirty != 0 {
		n += 2 + sovData(uint64(m.Dirty))
	}
	if m.Writeback != 0 {
		n += 2 + sovData(uint64(m.Writeback))
	}
	if m.AnonPages != 0 {
		n += 2 + sovData(uint64(m.AnonPages))
	}
	if m.Mapped != 0 {
		n += 2 + sovData(uint64(m.Mapped))
	}
	if m.Shmem != 0 {
		n += 2 + sovData(uint64(m.Shmem))
	}
	if m.Slab != 0 {
		n += 2 + sovData(uint64(m.Slab))
	}
	if m.SReclaimable != 0 {
		n += 2 + sovData(uint64(m.SReclaimable))
	}
	if m.SUnreclaim != 0 {
		n += 2 + sovData(uint64(m.SUnreclaim))
	}
	if m.KernelStack != 0 {
		n += 2 + sovData(uint64(m.KernelStack))
	}
	if m.NFSUnstable != 0 {
		n += 2 + sovData(uint64(m.NFSUnstable))
	}
	if m.Bounce != 0 {
		n += 2 + sovData(uint64(m.Bounce))
	}
	if m.WritebackTmp != 0 {
		n += 2 + sovData(uint64(m.WritebackTmp))
	}
	if m.CommitLimit != 0 {
		n += 2 + sovData(uint64(m.CommitLimit))
	}
	if m.VmallocTotal != 0 {
		n += 2 + sovData(uint64(m.VmallocTotal))
	}
	if m.VmallocUsed != 0 {
		n += 2 + sovData(uint64(m.VmallocUsed))
	}
	if m.VmallocChunk != 0 {
		n += 2 + sovData(uint64(m.VmallocChunk))
	}
	if m.HardwareCorrupted != 0 {
		n += 2 + sovData(uint64(m.HardwareCorrupted))
	}
	if m.AnonHugePages != 0 {
		n += 2 + sovData(uint64(m.AnonHugePages))
	}
	if m.HugePagesTotal != 0 {
		n += 2 + sovData(uint64(m.HugePagesTotal))
	}
	if m.HugePagesFree != 0 {
		n += 2 + sovData(uint64(m.HugePagesFree))
	}
	if m.HugePagesRsvd != 0 {
		n += 2 + sovData(uint64(m.HugePagesRsvd))
	}
	if m.Hugepagesize != 0 {
		n += 2 + sovData(uint64(m.Hugepagesize))
	}
	if m.DirectMap4K != 0 {
		n += 2 + sovData(uint64(m.DirectMap4K))
	}
	if m.DirectMap2M != 0 {
		n += 2 + sovData(uint64(m.DirectMap2M))
	}
	return n
}

func (m *GoGoSlickMessage) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.DestID != 0 {
		n += 1 + sovData(uint64(m.DestID))
	}
	if m.Type != 0 {
		n += 1 + sovData(uint64(m.Type))
	}
	if m.Kind != 0 {
		n += 1 + sovData(uint64(m.Kind))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	return n
}

func (m *GoGoSlickRedditAccount) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovData(uint64(l))
	}
	return n
}

func (m *GoGoSlickAccountData) Size() (n int) {
	var l int
	_ = l
	if m.CommentKarma != 0 {
		n += 1 + sovData(uint64(m.CommentKarma))
	}
	if m.HasMail {
		n += 2
	}
	if m.HasModMail {
		n += 2
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.InboxCount != 0 {
		n += 1 + sovData(uint64(m.InboxCount))
	}
	if m.IsFriend {
		n += 2
	}
	if m.IsGold {
		n += 2
	}
	if m.LinkKarma != 0 {
		n += 1 + sovData(uint64(m.LinkKarma))
	}
	l = len(m.ModHash)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.Over18 {
		n += 2
	}
	return n
}

func (m *GoGoSlickCPUInfo) Size() (n int) {
	var l int
	_ = l
	if len(m.CPUs) > 0 {
		for _, e := range m.CPUs {
			l = e.Size()
			n += 1 + l + sovData(uint64(l))
		}
	}
	return n
}

func (m *GoGoSlickCPU) Size() (n int) {
	var l int
	_ = l
	if m.Processor != 0 {
		n += 1 + sovData(uint64(m.Processor))
	}
	l = len(m.VendorID)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.CPUFamily)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.ModelName)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Stepping)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Microcode)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.CPUMHz != 0 {
		n += 5
	}
	l = len(m.CacheSize)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.PhysicalID != 0 {
		n += 1 + sovData(uint64(m.PhysicalID))
	}
	if m.Siblings != 0 {
		n += 1 + sovData(uint64(m.Siblings))
	}
	if m.CoreID != 0 {
		n += 1 + sovData(uint64(m.CoreID))
	}
	if m.CPUCores != 0 {
		n += 1 + sovData(uint64(m.CPUCores))
	}
	if m.ApicID != 0 {
		n += 1 + sovData(uint64(m.ApicID))
	}
	if m.InitialApicID != 0 {
		n += 1 + sovData(uint64(m.InitialApicID))
	}
	l = len(m.FPU)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.FPUException)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.CPUIDLevel)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.WP)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.Flags)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	if m.BogoMIPS != 0 {
		n += 6
	}
	l = len(m.CLFlushSize)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.CacheAlignment)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.AddressSizes)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	l = len(m.PowerManagement)
	if l > 0 {
		n += 2 + l + sovData(uint64(l))
	}
	return n
}

func sovData(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozData(x uint64) (n int) {
	return sovData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GoGoSlickBasicMemInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickBasicMemInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickBasicMemInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemTotal", wireType)
			}
			m.MemTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemFree", wireType)
			}
			m.MemFree = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemFree |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemAvailable", wireType)
			}
			m.MemAvailable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemAvailable |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffers", wireType)
			}
			m.Buffers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Buffers |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cached", wireType)
			}
			m.Cached = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Cached |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapCached", wireType)
			}
			m.SwapCached = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapCached |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapTotal", wireType)
			}
			m.SwapTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFree", wireType)
			}
			m.SwapFree = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapFree |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickMemInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickMemInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickMemInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemTotal", wireType)
			}
			m.MemTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemFree", wireType)
			}
			m.MemFree = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemFree |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemAvailable", wireType)
			}
			m.MemAvailable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.MemAvailable |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffers", wireType)
			}
			m.Buffers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Buffers |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cached", wireType)
			}
			m.Cached = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Cached |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapCached", wireType)
			}
			m.SwapCached = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapCached |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			m.Active = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Active |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inactive", wireType)
			}
			m.Inactive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Inactive |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveAnon", wireType)
			}
			m.ActiveAnon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ActiveAnon |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InactiveAnon", wireType)
			}
			m.InactiveAnon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.InactiveAnon |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveFile", wireType)
			}
			m.ActiveFile = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ActiveFile |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InactiveFile", wireType)
			}
			m.InactiveFile = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.InactiveFile |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unevictable", wireType)
			}
			m.Unevictable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Unevictable |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mlocked", wireType)
			}
			m.Mlocked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Mlocked |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapTotal", wireType)
			}
			m.SwapTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFree", wireType)
			}
			m.SwapFree = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SwapFree |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dirty", wireType)
			}
			m.Dirty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Dirty |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Writeback", wireType)
			}
			m.Writeback = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Writeback |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonPages", wireType)
			}
			m.AnonPages = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.AnonPages |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mapped", wireType)
			}
			m.Mapped = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Mapped |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shmem", wireType)
			}
			m.Shmem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Shmem |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slab", wireType)
			}
			m.Slab = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Slab |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SReclaimable", wireType)
			}
			m.SReclaimable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SReclaimable |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SUnreclaim", wireType)
			}
			m.SUnreclaim = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.SUnreclaim |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelStack", wireType)
			}
			m.KernelStack = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.KernelStack |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFSUnstable", wireType)
			}
			m.NFSUnstable = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.NFSUnstable |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bounce", wireType)
			}
			m.Bounce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Bounce |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WritebackTmp", wireType)
			}
			m.WritebackTmp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.WritebackTmp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitLimit", wireType)
			}
			m.CommitLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.CommitLimit |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmallocTotal", wireType)
			}
			m.VmallocTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.VmallocTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmallocUsed", wireType)
			}
			m.VmallocUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.VmallocUsed |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 32:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmallocChunk", wireType)
			}
			m.VmallocChunk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.VmallocChunk |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 33:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardwareCorrupted", wireType)
			}
			m.HardwareCorrupted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.HardwareCorrupted |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonHugePages", wireType)
			}
			m.AnonHugePages = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.AnonHugePages |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HugePagesTotal", wireType)
			}
			m.HugePagesTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.HugePagesTotal |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HugePagesFree", wireType)
			}
			m.HugePagesFree = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.HugePagesFree |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 37:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HugePagesRsvd", wireType)
			}
			m.HugePagesRsvd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.HugePagesRsvd |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 38:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hugepagesize", wireType)
			}
			m.Hugepagesize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Hugepagesize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 39:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectMap4K", wireType)
			}
			m.DirectMap4K = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DirectMap4K |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectMap2M", wireType)
			}
			m.DirectMap2M = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DirectMap2M |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickMessage) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = append(m.ID[:0], data[iNdEx:postIndex]...)
			if m.ID == nil {
				m.ID = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestID", wireType)
			}
			m.DestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DestID |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Type |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Kind |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], data[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickRedditAccount) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickRedditAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickRedditAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &GoGoSlickAccountData{}
			}
			if err := m.Data.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickAccountData) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickAccountData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickAccountData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommentKarma", wireType)
			}
			m.CommentKarma = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.CommentKarma |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasMail", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasMail = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasModMail", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasModMail = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboxCount", wireType)
			}
			m.InboxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.InboxCount |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFriend", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFriend = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsGold", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsGold = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkKarma", wireType)
			}
			m.LinkKarma = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.LinkKarma |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModHash = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Over18", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Over18 = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickCPUInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickCPUInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickCPUInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPUs = append(m.CPUs, &GoGoSlickCPU{})
			if err := m.CPUs[len(m.CPUs)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GoGoSlickCPU) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GoGoSlickCPU: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GoGoSlickCPU: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Processor", wireType)
			}
			m.Processor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Processor |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorID = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUFamily", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPUFamily = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelName = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stepping", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stepping = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Microcode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Microcode = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUMHz", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(data[iNdEx-4])
			v |= uint32(data[iNdEx-3]) << 8
			v |= uint32(data[iNdEx-2]) << 16
			v |= uint32(data[iNdEx-1]) << 24
			m.CPUMHz = float32(math.Float32frombits(v))
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CacheSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CacheSize = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhysicalID", wireType)
			}
			m.PhysicalID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.PhysicalID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Siblings", wireType)
			}
			m.Siblings = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Siblings |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoreID", wireType)
			}
			m.CoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.CoreID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUCores", wireType)
			}
			m.CPUCores = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.CPUCores |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApicID", wireType)
			}
			m.ApicID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ApicID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialApicID", wireType)
			}
			m.InitialApicID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.InitialApicID |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FPU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FPU = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FPUException", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FPUException = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPUIDLevel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPUIDLevel = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WP = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Flags = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field BogoMIPS", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(data[iNdEx-4])
			v |= uint32(data[iNdEx-3]) << 8
			v |= uint32(data[iNdEx-2]) << 16
			v |= uint32(data[iNdEx-1]) << 24
			m.BogoMIPS = float32(math.Float32frombits(v))
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CLFlushSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CLFlushSize = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CacheAlignment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CacheAlignment = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressSizes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressSizes = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerManagement", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PowerManagement = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipData(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthData
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowData
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipData(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthData = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowData   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorData = []byte{
	// 1328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xff, 0x27, 0xfe, 0x88, 0x77, 0xe2, 0x24, 0xcd, 0xfe, 0xdb, 0x74, 0x69, 0x4b, 0x28, 0xa6,
	0x94, 0x0a, 0xa1, 0x4a, 0x04, 0x2e, 0xb8, 0x42, 0xca, 0x07, 0x6e, 0xac, 0xc6, 0xc5, 0x5a, 0x37,
	0xad, 0xc4, 0xdd, 0x78, 0x76, 0xec, 0x1d, 0x79, 0xbf, 0xb4, 0xb3, 0xb6, 0x9b, 0x5e, 0xf7, 0x21,
	0x78, 0x18, 0x1e, 0x80, 0x4b, 0x1e, 0x01, 0xc1, 0x0d, 0x2f, 0x81, 0xc4, 0x39, 0x67, 0x66, 0xd7,
	0xeb, 0xaa, 0xe2, 0x9e, 0x8b, 0xb4, 0x7b, 0x7e, 0xe7, 0xfb, 0x63, 0xce, 0x31, 0x63, 0x01, 0x2f,
	0xf8, 0xd3, 0x2c, 0x4f, 0x8b, 0xd4, 0xed, 0xd0, 0x7f, 0x93, 0xc5, 0xb4, 0xf7, 0xf7, 0x16, 0xbb,
	0xf3, 0x2c, 0x7d, 0x96, 0x8e, 0x23, 0x25, 0xe6, 0x67, 0x5c, 0x2b, 0x31, 0x94, 0xf1, 0x20, 0x99,
	0xa6, 0xee, 0x3d, 0xd6, 0x81, 0xcf, 0x97, 0x69, 0xc1, 0x23, 0x6f, 0xeb, 0xe1, 0xd6, 0x93, 0x86,
	0xdf, 0x89, 0x2d, 0xed, 0x7a, 0x6c, 0x07, 0x78, 0xfd, 0x5c, 0x4a, 0x6f, 0x9b, 0x58, 0x3b, 0xb1,
	0x21, 0xdd, 0x1e, 0xeb, 0x02, 0xe7, 0x74, 0xc9, 0x55, 0xc4, 0x27, 0x91, 0xf4, 0x1a, 0xc4, 0xee,
	0xc6, 0x35, 0x0c, 0xb5, 0xcf, 0x16, 0xd3, 0xa9, 0xcc, 0xb5, 0xd7, 0x34, 0xda, 0x13, 0x43, 0xba,
	0x47, 0xac, 0x7d, 0xce, 0x45, 0x28, 0x03, 0xaf, 0x45, 0x8c, 0xb6, 0x20, 0xca, 0x3d, 0x66, 0x6c,
	0xbc, 0xe2, 0x99, 0xe5, 0xb5, 0x89, 0xc7, 0x74, 0x85, 0xb8, 0x0f, 0x98, 0x83, 0x7c, 0x13, 0xec,
	0x0e, 0xb1, 0x1d, 0x5d, 0x02, 0x98, 0x09, 0x72, 0x29, 0xdc, 0x8e, 0xc9, 0x44, 0x5b, 0xba, 0xf7,
	0x8e, 0xb1, 0x5b, 0x55, 0xfe, 0xff, 0xc5, 0xd4, 0x41, 0xef, 0x54, 0x14, 0x6a, 0x29, 0x6d, 0xde,
	0x6d, 0x4e, 0x14, 0xe6, 0x30, 0x48, 0xcc, 0x77, 0x99, 0xb4, 0xb2, 0x34, 0xda, 0x34, 0x3a, 0xa7,
	0x49, 0x9a, 0x78, 0x8e, 0xb1, 0xc9, 0x2b, 0x04, 0x33, 0x29, 0x75, 0x49, 0x82, 0x99, 0x4c, 0x54,
	0x0d, 0x5b, 0xdb, 0xe8, 0x2b, 0xc8, 0x75, 0xb7, 0x6e, 0x03, 0x91, 0xba, 0x0d, 0x92, 0xe8, 0x6e,
	0xda, 0x20, 0x99, 0x87, 0x6c, 0xf7, 0x3a, 0x91, 0x4b, 0x25, 0x0a, 0x2a, 0xd8, 0x1e, 0x89, 0xec,
	0x2e, 0xd6, 0x10, 0x55, 0x3b, 0x4a, 0xc5, 0x1c, 0x52, 0xdf, 0xb7, 0xd5, 0x36, 0xe4, 0x66, 0xcb,
	0x0f, 0xfe, 0xad, 0xe5, 0xb7, 0x36, 0x5b, 0xee, 0xde, 0x66, 0xad, 0x0b, 0x95, 0x17, 0x37, 0xde,
	0x21, 0x31, 0x5a, 0x01, 0x12, 0x68, 0xef, 0x75, 0xae, 0x0a, 0x39, 0xe1, 0x62, 0xee, 0xb9, 0xc6,
	0xde, 0xaa, 0x04, 0x90, 0x8b, 0x59, 0x8f, 0xf8, 0x4c, 0x6a, 0xef, 0xff, 0x86, 0xcb, 0x4b, 0x00,
	0x7b, 0x30, 0xe4, 0x59, 0x06, 0x41, 0xde, 0x36, 0x3d, 0x88, 0x89, 0x42, 0x4f, 0xe3, 0x10, 0xfa,
	0xef, 0xdd, 0x31, 0x9e, 0x34, 0x12, 0xae, 0xcb, 0x9a, 0x63, 0x98, 0x06, 0xef, 0x88, 0xc0, 0xa6,
	0x86, 0x6f, 0xac, 0xd6, 0xd8, 0x97, 0x22, 0xe2, 0x2a, 0xa6, 0x52, 0xdc, 0x35, 0xd5, 0xd2, 0x35,
	0x8c, 0x26, 0xe1, 0x3a, 0xc9, 0x0d, 0xe2, 0x79, 0x76, 0x12, 0x2a, 0x04, 0xab, 0xf9, 0x5c, 0xe6,
	0x89, 0x8c, 0xc6, 0x05, 0xe6, 0xf0, 0x91, 0xa9, 0xe6, 0x7c, 0x0d, 0xa1, 0xc4, 0x8b, 0x3e, 0xd8,
	0xd0, 0xa6, 0xde, 0xf7, 0x8c, 0x44, 0xb2, 0x86, 0x30, 0x93, 0xb3, 0x74, 0x91, 0x08, 0xe9, 0xdd,
	0x37, 0x99, 0x4c, 0x88, 0xc2, 0xf8, 0xaa, 0xea, 0xbc, 0x8c, 0x33, 0xef, 0x81, 0x89, 0x6f, 0x55,
	0xc3, 0xd0, 0xfa, 0x79, 0x1a, 0xc7, 0xaa, 0xb8, 0x52, 0xf0, 0x8f, 0xf7, 0xb1, 0xb1, 0x2e, 0xd6,
	0x10, 0x5a, 0x79, 0x15, 0xf3, 0x08, 0x3a, 0x68, 0xda, 0x76, 0x6c, 0xac, 0x2c, 0x6b, 0x18, 0x5a,
	0xb1, 0x32, 0xd7, 0x1a, 0x0a, 0xfa, 0x89, 0xb1, 0xb2, 0x5c, 0x43, 0x35, 0x2b, 0xe7, 0xe1, 0x22,
	0x99, 0x7b, 0x0f, 0x37, 0xac, 0x10, 0xe6, 0x7e, 0xc5, 0x0e, 0x2f, 0x79, 0x1e, 0xac, 0x78, 0x2e,
	0xcf, 0xd3, 0x3c, 0x5f, 0x64, 0x05, 0xd8, 0xfa, 0x94, 0x04, 0x0f, 0xc3, 0xf7, 0x19, 0xee, 0x23,
	0xb6, 0x87, 0xdd, 0xbd, 0x5c, 0xcc, 0xa4, 0xe9, 0x70, 0x8f, 0x24, 0xf7, 0x78, 0x1d, 0x74, 0x1f,
	0xb3, 0xfd, 0x8a, 0x30, 0xf1, 0x7f, 0x46, 0x62, 0xfb, 0xe1, 0x06, 0x8a, 0xd6, 0x2a, 0x39, 0x1a,
	0xc0, 0x47, 0xc6, 0x5a, 0x58, 0x07, 0x37, 0xa4, 0x7c, 0xbd, 0x0c, 0xbc, 0xcf, 0xdf, 0x93, 0x42,
	0x10, 0x73, 0x45, 0xa9, 0x0c, 0x01, 0xf5, 0x56, 0x7a, 0x8f, 0x4d, 0xae, 0x61, 0x0d, 0xc3, 0x8a,
	0xc1, 0x3c, 0x4b, 0x51, 0xc0, 0x0c, 0x7e, 0x3b, 0xf7, 0xbe, 0x30, 0x15, 0x0b, 0xd6, 0xd0, 0x86,
	0xc4, 0xc9, 0xd0, 0x7b, 0xf2, 0x9e, 0xc4, 0xc9, 0xb0, 0xb7, 0xdc, 0xd8, 0x82, 0x5a, 0x83, 0x6d,
	0x77, 0x9f, 0x6d, 0x0f, 0x2e, 0x68, 0xff, 0x75, 0xfd, 0x6d, 0x75, 0x81, 0xb3, 0x71, 0x21, 0x75,
	0x01, 0x18, 0x2e, 0xbe, 0x3d, 0xbf, 0x1d, 0x10, 0x85, 0xf3, 0xfc, 0xf2, 0x26, 0x33, 0xfb, 0xae,
	0xe5, 0x37, 0x0b, 0xf8, 0x46, 0xec, 0xb9, 0x4a, 0x02, 0x5a, 0x72, 0x80, 0xcd, 0xe1, 0x1b, 0xb1,
	0x0b, 0x38, 0x41, 0xb4, 0xdf, 0xba, 0x7e, 0x13, 0xcf, 0x51, 0xef, 0xdd, 0x16, 0x3b, 0xaa, 0x1c,
	0xfb, 0x32, 0x08, 0x54, 0x71, 0x2a, 0x04, 0xcc, 0x5c, 0x51, 0x73, 0xef, 0x90, 0x7b, 0x50, 0x7f,
	0xc1, 0x63, 0xb3, 0x75, 0x1d, 0xbf, 0x99, 0xc0, 0x77, 0xe5, 0xa6, 0x61, 0x30, 0x72, 0x73, 0x62,
	0xdd, 0xa0, 0xeb, 0xdd, 0x93, 0xe3, 0xa7, 0xe5, 0xa9, 0x7b, 0x5a, 0xf9, 0xb1, 0x1e, 0x50, 0xca,
	0x86, 0xf1, 0xcb, 0x36, 0xbb, 0xfd, 0x21, 0x36, 0xd6, 0x1f, 0x67, 0x5a, 0x26, 0xc5, 0x73, 0x9e,
	0xc7, 0xdc, 0x5e, 0x83, 0xae, 0xa8, 0x61, 0xb8, 0xa3, 0x2e, 0xb9, 0x1e, 0xc2, 0x8a, 0xa7, 0xd8,
	0x3a, 0xfe, 0x4e, 0x68, 0x48, 0x7c, 0xb1, 0xc8, 0x49, 0x03, 0x62, 0x36, 0x88, 0xc9, 0xc2, 0x0a,
	0xb1, 0x29, 0x36, 0xab, 0x14, 0x41, 0x7e, 0x90, 0x4c, 0xd2, 0x37, 0xe7, 0xe8, 0xdf, 0xde, 0x01,
	0xa6, 0x2a, 0x84, 0x76, 0x3a, 0x4c, 0x8f, 0x92, 0x89, 0xb9, 0x04, 0x1d, 0xd8, 0xe9, 0x96, 0xc6,
	0xee, 0x0c, 0xf4, 0xb3, 0x34, 0x0a, 0xe8, 0x0e, 0x74, 0xfc, 0xb6, 0x22, 0x0a, 0x37, 0xd7, 0x95,
	0x4a, 0xe6, 0x26, 0x7c, 0x73, 0x08, 0x9c, 0xa8, 0x04, 0x68, 0xbf, 0xa6, 0x01, 0x04, 0x19, 0xd2,
	0x19, 0x70, 0x60, 0xbf, 0x1a, 0xb2, 0x2a, 0x37, 0xab, 0x95, 0x1b, 0x7c, 0xfc, 0xb8, 0x94, 0xf9,
	0xd7, 0xdf, 0xd1, 0xbe, 0x07, 0x1f, 0x29, 0x51, 0xbd, 0xef, 0x6b, 0xd3, 0x73, 0x3e, 0xba, 0xa6,
	0x1b, 0xfa, 0x25, 0x6b, 0xc2, 0xa7, 0x86, 0x8a, 0x35, 0xa0, 0x0d, 0x47, 0x1f, 0x68, 0x03, 0xb0,
	0xfd, 0xa6, 0x00, 0x99, 0xde, 0x5f, 0x2d, 0xd6, 0xad, 0xc3, 0x18, 0xf4, 0x28, 0x4f, 0x05, 0x0c,
	0x62, 0x9a, 0x53, 0xcd, 0x5b, 0xbe, 0x93, 0x95, 0x00, 0x96, 0xe1, 0x15, 0xa4, 0x9c, 0xe6, 0x76,
	0x14, 0x1d, 0xbf, 0xb3, 0xb4, 0x34, 0x6a, 0x82, 0x81, 0x3e, 0x8f, 0x55, 0x74, 0x63, 0xc7, 0xc2,
	0x11, 0x25, 0x80, 0x0b, 0x19, 0xd2, 0x95, 0x91, 0xad, 0x79, 0x2b, 0x46, 0x02, 0x75, 0x08, 0xa5,
	0x7c, 0x5b, 0x46, 0x27, 0x2e, 0x01, 0x3a, 0x25, 0x85, 0xcc, 0x32, 0x95, 0xcc, 0xa8, 0xe8, 0xe0,
	0x4d, 0x5b, 0x9a, 0x34, 0x95, 0x80, 0xc0, 0x40, 0x9a, 0xea, 0x8e, 0x9a, 0x25, 0x40, 0x27, 0x7d,
	0x74, 0x3d, 0xbc, 0x7c, 0x4b, 0x75, 0xdf, 0x86, 0x93, 0x4e, 0x14, 0xc5, 0x88, 0xc7, 0x7b, 0x8c,
	0x2f, 0xda, 0xb1, 0x31, 0x96, 0x00, 0x0e, 0xc1, 0x28, 0xbc, 0x81, 0x1f, 0x62, 0x3c, 0x82, 0xfc,
	0x18, 0x25, 0xcf, 0xb2, 0x0a, 0xa1, 0x78, 0xd4, 0x04, 0x5a, 0x38, 0xd3, 0xd4, 0x86, 0x16, 0xc4,
	0x63, 0x69, 0xf2, 0x98, 0xe6, 0x12, 0xf4, 0xba, 0xc4, 0x69, 0x0b, 0xa2, 0x50, 0x07, 0x22, 0x41,
	0x96, 0xa6, 0x2b, 0x0b, 0x3a, 0xc2, 0xd2, 0xf4, 0x03, 0x22, 0x53, 0x02, 0x74, 0xf6, 0x8d, 0x0e,
	0x27, 0x0a, 0x17, 0xd4, 0x20, 0x51, 0x85, 0xe2, 0x91, 0x65, 0x1f, 0x10, 0x7b, 0x4f, 0xd5, 0x41,
	0xf7, 0x16, 0x6b, 0xf4, 0x47, 0xd7, 0x74, 0x63, 0x1d, 0xbf, 0x31, 0x85, 0xde, 0xc1, 0x93, 0x01,
	0xe4, 0x87, 0x37, 0x42, 0x66, 0x85, 0x82, 0x1f, 0x0f, 0x87, 0xc4, 0xea, 0x4e, 0x6b, 0x18, 0xe6,
	0x88, 0x73, 0x72, 0x71, 0x25, 0x97, 0xd0, 0x0c, 0x97, 0x24, 0x98, 0xa8, 0x10, 0x7c, 0x18, 0xaf,
	0x47, 0x74, 0x67, 0xe1, 0x61, 0xac, 0x46, 0xd8, 0xb7, 0x7e, 0xc4, 0x21, 0xe1, 0x3b, 0xa6, 0x6f,
	0x53, 0x24, 0x30, 0xab, 0xb3, 0x74, 0x96, 0x0e, 0x07, 0xa3, 0x31, 0x1d, 0xd3, 0x6d, 0xbf, 0x33,
	0xb1, 0x34, 0x1d, 0xa3, 0xab, 0x7e, 0xb4, 0xd0, 0x21, 0x55, 0xf9, 0x2e, 0xe9, 0xed, 0x8a, 0x35,
	0x84, 0xeb, 0x9c, 0xba, 0x70, 0x1a, 0xa9, 0x59, 0x82, 0xaf, 0x99, 0x4e, 0xaa, 0xe3, 0xef, 0x8b,
	0x0d, 0x14, 0xf3, 0x39, 0x0d, 0x02, 0xa8, 0x94, 0x46, 0x35, 0x4d, 0x77, 0x15, 0xf2, 0xe1, 0x35,
	0xcc, 0x7d, 0xc2, 0x0e, 0x46, 0xe9, 0x4a, 0xe6, 0x43, 0x9e, 0xc0, 0xe6, 0x24, 0x63, 0xf7, 0x48,
	0xec, 0x20, 0xdb, 0x84, 0xcf, 0xee, 0xff, 0xfa, 0xc7, 0xf1, 0xd6, 0x6f, 0xf0, 0xf7, 0x3b, 0xfc,
	0xfd, 0xfc, 0xe7, 0xf1, 0xff, 0x7e, 0x72, 0x66, 0x10, 0xb3, 0xc6, 0xc9, 0x9f, 0xb4, 0xe9, 0x91,
	0x7c, 0xf3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x97, 0xda, 0x0c, 0xab, 0x0b, 0x00, 0x00,
}
