// Code generated by "stringer -type=Proto"; DO NOT EDIT

package shared

import "fmt"

const _Proto_name = "UnknownProtFlatbuffersJSONFFJSONProtobufV3CapnProto2"

var _Proto_index = [...]uint8{0, 11, 22, 26, 32, 42, 52}

func (i Proto) String() string {
	if i < 0 || i >= Proto(len(_Proto_index)-1) {
		return fmt.Sprintf("Proto(%d)", i)
	}
	return _Proto_name[_Proto_index[i]:_Proto_index[i+1]]
}
