// Code generated by "stringer -type=StructType"; DO NOT EDIT

package shared

import "fmt"

const _StructType_name = "UnknownStructBasicMemInfoMemInfoMessageRedditAccountCPUInfo"

var _StructType_index = [...]uint8{0, 13, 25, 32, 39, 52, 59}

func (i StructType) String() string {
	if i < 0 || i >= StructType(len(_StructType_index)-1) {
		return fmt.Sprintf("StructType(%d)", i)
	}
	return _StructType_name[_StructType_index[i]:_StructType_index[i+1]]
}
